name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci
      
    - run: npm test
      
    - run: npm start &
    - run: newman run './tests/CoronaDashboard.postman_collection.json'

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'corona-dashboard'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b1c9de0d9c5b42b1b58658c9a0326706 }}
        package: .
